"""Structural display requirements at the reviewed Klipper revisions.

These checks do not establish electrical compatibility or replace Klipper's
complete configuration loading and MCU validation.
"""
from core.exceptions import GenerationError


DISPLAY_REQUIRED_OPTIONS = {
    "st7920": ("cs_pin", "sclk_pin", "sid_pin"),
    "hd44780": ("rs_pin", "e_pin", "d4_pin", "d5_pin", "d6_pin", "d7_pin"),
    "emulated_st7920": ("en_pin", "spi_software_miso_pin", "spi_software_mosi_pin", "spi_software_sclk_pin"),
    "hd44780_spi": ("latch_pin",),
    "aip31068_spi": ("latch_pin",),
    "uc1701": ("cs_pin", "a0_pin"),
    "ssd1306": (),
    "sh1106": (),
}


def validate_generated_display_artifacts(
    hardware: bytes, macros: bytes | None = None, *, included_files: dict | None = None,
) -> None:
    """Recheck generated bytes, never saved compatibility/consent labels.

    Generated payloads carry no reviewed module/wiring evidence. Existing manual
    destination sections have a separate structural review and are not inputs
    here. Legacy controller-named sections must not bypass the same boundary.
    When destination files are available, follow only generated include roots
    using the deployment expander and its existing path/size/cycle constraints.
    """
    if included_files is not None:
        from core.managed_config import ROOT_REMOTE, MACROS_REMOTE, ManagedConfigPlan, effective_hardware_text
        files = dict(included_files)
        files[ROOT_REMOTE] = hardware
        if macros is not None:
            files[MACROS_REMOTE] = macros
            files[ROOT_REMOTE] += f"\n[include {MACROS_REMOTE}]\n".encode()
        try:
            expanded = effective_hardware_text(ManagedConfigPlan((), source_files=tuple(files.items())))
        except (ValueError, UnicodeError) as exc:
            raise GenerationError(f"Generated display include review failed: {exc}") from exc
        validate_generated_display_artifacts(expanded.encode('utf-8'))
        return
    from core.display_checker import get_all_selectable_displays, classify_hardware_combination
    from core.pin_validator import PinAliasError, _read_pin_config

    physical = {key for key, _ in get_all_selectable_displays()}
    for filename, content in (("printer.cfg", hardware), ("macros.cfg", macros)):
        if content is None:
            continue
        try:
            sections = _read_pin_config(content.decode("utf-8"))[0]
        except (UnicodeError, PinAliasError) as exc:
            raise GenerationError(f"Generated configuration {filename} cannot be read for display review: {exc}") from exc
        for name in sections:
            if name.split()[0] not in physical:
                continue
            result = classify_hardware_combination(name, "", sections)
            if result.get("hardware_evidence") == "unknown" or result["compatibility_class"] != "fully_compatible":
                raise GenerationError(
                    f"Generated display hardware in {filename} [{name}] has no verified module/wiring evidence "
                    "or is classified unsafe. Reload the configuration and regenerate before deployment; "
                    "saved compatibility labels and accepted risk do not establish hardware evidence."
                )


def validate_display_config(sections: dict) -> None:
    """Check active display driver/required fields after include expansion."""
    for name, options in sections.items():
        if name != "display" and not name.startswith("display "):
            continue
        driver = options.get("lcd_type", "")
        if driver not in DISPLAY_REQUIRED_OPTIONS:
            raise GenerationError(f"[{name}] requires a supported Klipper lcd_type; received {driver!r}.")
        required = list(DISPLAY_REQUIRED_OPTIONS[driver])
        if driver in ("ssd1306", "sh1106") and "cs_pin" in options:
            required += ["cs_pin", "dc_pin"]
        spi = driver in ("hd44780_spi", "aip31068_spi", "uc1701", "emulated_st7920") or (
            driver in ("ssd1306", "sh1106") and "cs_pin" in options)
        if spi and "spi_software_sclk_pin" in options:
            required += ["spi_software_miso_pin", "spi_software_mosi_pin", "spi_software_sclk_pin"]
        if driver in ("ssd1306", "sh1106") and not spi and "i2c_software_scl_pin" in options:
            required += ["i2c_software_scl_pin", "i2c_software_sda_pin"]
        missing = [key for key in dict.fromkeys(required) if not str(options.get(key, "")).strip()]
        if missing:
            raise GenerationError(f"[{name}] ({driver}) requires: {', '.join(missing)}.")
