import os
from core.translations import t

def generate_first_steps_guide() -> str:
    """Generates a post-install calibration guide in the KACE directory."""
    guide_content = """# Klipper Post-Install Calibration & First Steps

Welcome to Klipper! This guide outlines the essential steps to safely bring up your printer and tune it for optimal performance.

## ⚠️ Important Safety Warning
Do NOT home (G28) your printer until you have verified that your endstops and stepper motor directions are correct. Crashing your nozzle into the bed can damage your hardware.

---

## 1. Essential Bring-Up

### 1.1. System Check
1. Power on your printer.
2. Open Mainsail/Fluidd.
3. Verify that Klipper connects and reports `Ready`. If you see an error, check the console logs.
   *Command:* `FIRMWARE_RESTART` (if needed)

### 1.2. Verify Heaters & Thermistors
1. Check that the hotend and bed temperatures reported in the web UI match your room temperature.
2. Turn on the hotend to 50°C and verify it heats up. Turn it off immediately.
3. Repeat for the heated bed.

### 1.3. Verify Endstops & Probes
1. Manually move the print head to the center of the bed.
2. Run the `QUERY_ENDSTOPS` command in the console.
3. Manually trigger each endstop switch (X, Y, Z) while holding it, and run `QUERY_ENDSTOPS` again to ensure it changes from `open` to `TRIGGERED`.
4. If using a BLTouch/CR-Touch, deploy and retract it using `BLTOUCH_DEBUG COMMAND=pin_down` and `BLTOUCH_DEBUG COMMAND=pin_up`.

### 1.4. Stepper Motor Direction Test
1. Send `STEPPER_BUZZ STEPPER=stepper_x`. The toolhead should move +1mm, then -1mm.
2. Repeat for `stepper_y` and `stepper_z`.
3. If any motor moves in the wrong direction, edit your `printer.cfg` and add or remove the `!` in front of the `dir_pin` for that stepper.

### 1.5. Extruder Direction Test
1. Heat the hotend to printing temperature (e.g., 200°C).
2. Extrude 10mm of filament.
3. If the filament retracts instead of extruding, invert the extruder's `dir_pin` in `printer.cfg`.

### 1.6. First Homing
1. With one hand on the power switch, send `G28 X` and `G28 Y`. If it moves the wrong way or crashes, cut power immediately.
2. Move the nozzle to the center of the bed.
3. Send `G28 Z` (or `G28` for all axes) and be ready to trigger the Z-endstop or probe with your finger to ensure it stops.

### 1.7. PID Tuning
Run these commands one at a time, wait for them to finish, and save.
1. Hotend: `PID_CALIBRATE HEATER=extruder TARGET=200`
2. Bed: `PID_CALIBRATE HEATER=heater_bed TARGET=60`
3. Save: `SAVE_CONFIG`

### 1.8. Probe Calibration & Bed Mesh
1. If using a probe, run `PROBE_CALIBRATE` and follow the paper test to set your Z-offset.
2. Run `BED_MESH_CALIBRATE` to generate your first bed mesh.
3. Save: `SAVE_CONFIG`

---

## 2. Advanced Tuning

Once your printer is printing reliably, consider these advanced tuning steps to improve quality and speed:

### 2.1. Pressure Advance
Pressure Advance reduces oozing and corner bulging by predicting extruder pressure.
* **Goal:** Sharper corners and cleaner line ends.
* **Guide:** See the Klipper documentation on Pressure Advance calibration.

### 2.2. Resonance Testing & Input Shaper
Input Shaper cancels out mechanical vibrations (ringing/ghosting) at high speeds.
* **Goal:** Smoother prints at much higher accelerations.
* **Guide:** Use an ADXL345 accelerometer or manually print the ringing tower test to find your frequency.

---
*Generated by KACE (Klipper Automated Configuration Ecosystem)*
"""
    
    base_path = os.path.expanduser('~/kace')
    os.makedirs(base_path, exist_ok=True)
    guide_path = os.path.join(base_path, 'first_steps.md')
    
    with open(guide_path, 'w', encoding='utf-8') as f:
        f.write(guide_content)
        
    return guide_path
