"""Plan KACE-owned configuration updates without mutating a live printer.

KACE owns generated files below ``kace/`` and one small include block in the
user's root ``printer.cfg``. Everything else remains user-owned. The planner is
pure: callers supply remote bytes and receive immutable artifacts plus a diff.
"""

from __future__ import annotations

import difflib
import posixpath
import re
from dataclasses import dataclass
from typing import Mapping, Optional

from core.reconciler import reconcile_moonraker_conf_content


HARDWARE_REMOTE = "kace/generated-hardware.cfg"
MACROS_REMOTE = "kace/generated-macros.cfg"
LEGACY_MACROS_REMOTE = "macros.cfg"
ROOT_REMOTE = "printer.cfg"
MOONRAKER_REMOTE = "moonraker.conf"
MANAGED_BEGIN = "# BEGIN KACE MANAGED: generated-includes"
MANAGED_END = "# END KACE MANAGED: generated-includes"

_SECTION_RE = re.compile(r"(?m)^\s*\[([^\]\r\n]+)\]\s*(?:[#;].*)?$")
_SAVE_CONFIG_RE = re.compile(
    r"(?m)^#\*# <---------------------- SAVE_CONFIG ---------------------->[ \t]*\r?$"
)
_MANAGED_RE = re.compile(
    rf"(?ms)^\s*{re.escape(MANAGED_BEGIN)}\r?\n.*?^\s*{re.escape(MANAGED_END)}\s*(?:\r?\n)?"
)
_LEGACY_HEADER = "# This file was generated by KACE (Klipper Automated Configuration Ecosystem)"

# These are tuning values users commonly calibrate after initial generation.
# They are migrated into the KACE-owned hardware file instead of being reset.
_PRESERVED_OPTIONS = {
    "printer": {
        "max_velocity", "max_accel", "max_z_velocity", "max_z_accel",
        "square_corner_velocity", "minimum_cruise_ratio",
    },
    "extruder": {
        "pid_kp", "pid_ki", "pid_kd", "pressure_advance",
        "pressure_advance_smooth_time", "nozzle_diameter", "filament_diameter",
    },
    "heater_bed": {"pid_kp", "pid_ki", "pid_kd"},
    "force_move": {"enable_force_move"},
    "probe": {"z_offset"},
    "bltouch": {"z_offset"},
    "input_shaper": {"shaper_freq_x", "shaper_freq_y", "shaper_type_x", "shaper_type_y"},
}
_PRESERVED_PREFIX_OPTIONS = {
    "stepper_": {"microsteps", "rotation_distance", "gear_ratio", "homing_speed", "position_endstop"},
    "tmc": {"run_current", "hold_current", "stealthchop_threshold", "interpolate"},
}


@dataclass(frozen=True)
class PlannedConfigArtifact:
    remote_name: str
    content: bytes
    previous: Optional[bytes]

    @property
    def existed(self) -> bool:
        return self.previous is not None

    @property
    def changed(self) -> bool:
        return self.previous != self.content

    def unified_diff(self) -> str:
        before = (self.previous or b"").decode("utf-8", errors="replace").splitlines(True)
        after = self.content.decode("utf-8", errors="replace").splitlines(True)
        return "".join(difflib.unified_diff(
            before,
            after,
            fromfile=f"remote/{self.remote_name}",
            tofile=f"planned/{self.remote_name}",
            n=0,
        ))


@dataclass(frozen=True)
class ManagedConfigPlan:
    artifacts: tuple[PlannedConfigArtifact, ...]
    legacy_migration: bool = False
    warnings: tuple[str, ...] = ()
    source_files: tuple[tuple[str, Optional[bytes]], ...] = ()

    @property
    def remote_names(self) -> tuple[str, ...]:
        return tuple(item.remote_name for item in self.artifacts)

    @property
    def changed_artifacts(self) -> tuple[PlannedConfigArtifact, ...]:
        return tuple(item for item in self.artifacts if item.changed)

    def dry_run_diff(self) -> str:
        return "\n".join(diff for item in self.artifacts if (diff := item.unified_diff()))


def _newline(text: str) -> str:
    return "\r\n" if "\r\n" in text else "\n"


def _section_spans(text: str):
    matches = list(_SECTION_RE.finditer(text))
    for index, match in enumerate(matches):
        yield (
            match.group(1).strip(),
            match.start(),
            matches[index + 1].start() if index + 1 < len(matches) else len(text),
        )


def _section_options(text: str) -> dict[str, dict[str, str]]:
    result: dict[str, dict[str, str]] = {}
    for name, start, end in _section_spans(text):
        options: dict[str, str] = {}
        header_end = text.find("\n", start, end)
        body = text[header_end + 1:end] if header_end >= 0 else ""
        previous_option = None
        option_indent = 0
        for line in body.splitlines():
            if not line.strip() or line.lstrip().startswith(("#", ";")):
                continue
            indent = len(line) - len(line.lstrip())
            if previous_option is not None and indent > option_indent:
                options[previous_option] += "\n" + line.strip()
                continue
            match = re.match(r"^\s*([^:=#;]+?)\s*[:=]\s*(.*?)\s*(?:[#;].*)?$", line)
            if match:
                previous_option = match.group(1).strip().casefold()
                option_indent = indent
                options[previous_option] = match.group(2).strip()
            else:
                previous_option = None
        result.setdefault(name.casefold(), {}).update(options)
    return result


def _setting_loss_warnings(source: str, before: str, after: str) -> tuple[str, ...]:
    """Expose replaced/removed settings in the normal pre-deployment review."""
    planned = _section_options(after)
    warnings = []
    for section, options in _section_options(before).items():
        if section.startswith("include "):
            continue  # Expanded dependencies are not removed config sections.
        if not options and section not in planned:
            warnings.append(f"{source}: [{section}] will be removed.")
        for option, value in options.items():
            replacement = planned.get(section, {}).get(option)
            if replacement == value:
                continue
            action = "removed" if replacement is None else f"replaced with {replacement!r}"
            warnings.append(
                f"{source}: [{section}] {option} = {value!r} will be {action}."
            )
    return tuple(warnings)


def _preserved_names(section: str) -> set[str]:
    folded = section.casefold()
    names = set(_PRESERVED_OPTIONS.get(folded, set()))
    for prefix, values in _PRESERVED_PREFIX_OPTIONS.items():
        if folded.startswith(prefix):
            names.update(values)
    return names


def _replace_or_insert_option(text: str, section: str, option: str, value: str) -> str:
    for name, start, end in _section_spans(text):
        if name.casefold() != section.casefold():
            continue
        body = text[start:end]
        pattern = re.compile(
            rf"(?mi)^(\s*{re.escape(option)}\s*[:=]\s*)([^#;\r\n]*?)(\s*)((?:[#;].*)?)$"
        )
        if pattern.search(body):
            replacement = pattern.sub(
                lambda m: f"{m.group(1)}{value}{m.group(3)}{m.group(4)}",
                body,
                count=1,
            )
        else:
            nl = _newline(text)
            replacement = body.rstrip("\r\n") + f"{nl}{option}: {value}{nl}"
        return text[:start] + replacement + text[end:]
    return text


def _carry_user_tuning(generated: str, existing_root: str) -> str:
    existing = _section_options(existing_root)
    generated_options = _section_options(generated)
    generated_sections = set(generated_options)
    for section, options in existing.items():
        if section not in generated_sections:
            continue
        for option in _preserved_names(section):
            if (
                section in {"extruder", "heater_bed"}
                and option.startswith("pid_")
                and generated_options.get(section, {}).get("control", "").casefold() != "pid"
            ):
                continue
            if option in options:
                generated = _replace_or_insert_option(generated, section, option, options[option])
    return generated


def _extract_generated_includes(generated: str) -> tuple[str, list[str]]:
    includes: list[str] = []
    spans = list(_section_spans(generated))
    for name, start, end in reversed(spans):
        if name.casefold().startswith("include "):
            includes.insert(0, f"[{name}]")
            generated = generated[:start] + generated[end:]
    return generated.strip() + "\n", includes


def _strip_owned_sections(root: str, owned_sections: set[str]) -> str:
    spans = list(_section_spans(root))
    for name, start, end in reversed(spans):
        folded = name.casefold()
        if folded.startswith("include "):
            continue
        if folded in owned_sections:
            root = root[:start] + root[end:]
    return root


def _managed_block(extra_includes: list[str], include_macros: bool, newline: str) -> str:
    lines = [MANAGED_BEGIN]
    lines.extend(extra_includes)
    lines.append(f"[include {HARDWARE_REMOTE}]")
    if include_macros:
        lines.append(f"[include {MACROS_REMOTE}]")
    lines.append(MANAGED_END)
    return newline.join(lines) + newline


def _has_include(text: str, remote_name: str) -> bool:
    wanted = f"include {remote_name}".casefold()
    return any(name.casefold() == wanted for name, _, _ in _section_spans(text))


def _remove_include(text: str, remote_name: str) -> str:
    wanted = f"include {remote_name}".casefold()
    for name, start, end in reversed(list(_section_spans(text))):
        if name.casefold() == wanted:
            text = text[:start] + text[end:]
    return text


def _autosave_text(text: str) -> str:
    return "\n".join(line[4:] for line in text.splitlines() if line.startswith("#*# "))


def _root_calibration(generated: str, saved: str, active: str = "") -> tuple[str, str]:
    """Keep SAVE_CONFIG-writable defaults in the root, outside includes.

    Klipper comments options out of its root when saving; it cannot do that
    inside an include. Existing autosave values must not be shadowed by defaults.
    """
    saved_options = _section_options(_autosave_text(saved))
    active_options = _section_options(active)
    fragments = []
    for section, start, end in reversed(list(_section_spans(generated))):
        folded = section.casefold()
        options = _section_options(generated[start:end]).get(folded, {})
        names = set(saved_options.get(folded, {}))
        if folded in {"extruder", "heater_bed"} or folded.startswith("heater_generic "):
            names.add("control")
            if options.get("control", "").casefold() == "pid":
                names.update({"control", "pid_kp", "pid_ki", "pid_kd"})
            elif set(saved_options.get(folded, {})) & {"control", "pid_kp", "pid_ki", "pid_kd"}:
                raise ValueError(f"[{section}] saved heater calibration conflicts with the selected control mode; resolve SAVE_CONFIG first")
        if folded in {"probe", "bltouch"} or folded.startswith("probe "):
            names.add("z_offset")
        if folded.startswith("stepper_"):
            names.add("position_endstop")
        if folded == "input_shaper":
            names.update({"shaper_freq_x", "shaper_freq_y", "shaper_type_x", "shaper_type_y"})
        kept, moved = [], []
        moving = False
        for line in generated[start:end].splitlines(True):
            match = re.match(r"^([^\s#;\[=:]+)\s*[:=]", line)
            if match:
                option = match.group(1).casefold()
                moving = option in names
                retain_default = (option not in saved_options.get(folded, {})
                                  or (option in active_options.get(folded, {})
                                      and options.get(option) == active_options[folded][option]))
            elif line.strip() and not line[0].isspace():
                moving = False
            if moving:
                if retain_default:
                    moved.append(line)
            else:
                kept.append(line)
        if moved:
            fragments.insert(0, f"[{section}]\n" + "".join(moved).rstrip() + "\n")
        generated = generated[:start] + "".join(kept) + generated[end:]
    return generated, "\n".join(fragments)


def config_includes(content: bytes, source: str):
    """Resolve explicit relative includes; reject unreviewable path patterns."""
    for line in content.decode("utf-8").splitlines():
        # Klipper processes includes at column zero, stripping '#' first.
        match = re.match(r"\[include ([^\]]+)\]", line.split("#", 1)[0])
        if not match:
            continue
        spec = match.group(1).strip()
        name = posixpath.normpath(posixpath.join(posixpath.dirname(source), spec))
        if (not spec or spec.startswith("/") or "\\" in spec
                or name == ".." or name.startswith("../") or ":" in spec
                or any(char in spec for char in "*?[")):
            raise ValueError(f"Include {spec!r} in {source} cannot be reviewed safely; use explicit files inside the config root")
        yield line, name


def effective_hardware_text(plan: ManagedConfigPlan, *, strict: bool = True) -> str:
    """Expand includes in Klipper's linear order, including user-owned files."""
    files = {name: value.decode("utf-8") for name, value in plan.source_files if value is not None}
    files.update({item.remote_name: item.content.decode("utf-8") for item in plan.artifacts})
    expanded_bytes = 0

    def expand(name, stack=()):
        nonlocal expanded_bytes
        if name in stack or len(stack) >= 32:
            raise ValueError(f"recursive or excessively nested include: {name}")
        if name not in files:
            if not strict:
                return ""
            raise ValueError(f"Include file was not read for review: {name}")
        expanded_bytes += len(files[name].encode("utf-8"))
        if expanded_bytes > 8 * 1024 * 1024:
            raise ValueError("expanded configuration exceeds review limits")
        includes = dict(config_includes(files[name].encode("utf-8"), name))
        return "\n".join(expand(includes[line], (*stack, name)) if line in includes else line
                         for line in files[name].splitlines()) + "\n"

    text = expand(ROOT_REMOTE)
    active = _section_options(text)
    saved = _section_options(_autosave_text(files.get(ROOT_REMOTE, "")))
    for section, options in saved.items():
        missing = {key: value for key, value in options.items() if key not in active.get(section, {})}
        if missing:
            text += f"\n[{section}]\n" + "\n".join(
                f"{key}: " + value.replace("\n", "\n    ") for key, value in missing.items()
            ) + "\n"
    return text


def _reconcile_root(existing: str, generated: str, include_macros: bool, saved: str = "", active: str = "") -> tuple[str, str, bool]:
    nl = _newline(existing or generated)
    generated, generated_includes = _extract_generated_includes(generated)
    owned = {name.casefold() for name, _, _ in _section_spans(generated)}
    migrated = _LEGACY_HEADER in existing and MANAGED_BEGIN not in existing

    begin_count = existing.count(MANAGED_BEGIN)
    end_count = existing.count(MANAGED_END)
    if begin_count != end_count or begin_count > 1:
        raise ValueError("printer.cfg contains malformed or duplicate KACE managed markers")

    if _MANAGED_RE.search(existing):
        base = _MANAGED_RE.sub("", existing, count=1)
    else:
        base = existing
    # Bootstrap and external tools may have reintroduced generated-owned
    # sections after KACE's marker block was created. Ownership is based on
    # section identity, not on whether the marker already existed.
    base = _strip_owned_sections(base, owned)

    # Do not duplicate an existing user-owned include. KACE only owns its
    # generated include entries; Mainsail/Fluidd and custom includes survive.
    existing_include_names = {
        name.casefold() for name, _, _ in _section_spans(base)
        if name.casefold().startswith("include ")
    }
    extra = [line for line in generated_includes if line[1:-1].casefold() not in existing_include_names]
    block = _managed_block(extra, include_macros, nl)
    generated, calibration = _root_calibration(generated, saved, active)
    if calibration:
        block = block.replace(MANAGED_END, calibration.replace("\n", nl) + MANAGED_END)
    base = base.lstrip("\r\n")
    reconciled = block + (nl if base else "") + base
    if not reconciled.endswith(nl):
        reconciled += nl
    return reconciled, generated, migrated


def build_managed_config_plan(
    generated_hardware: bytes,
    generated_macros: Optional[bytes],
    remote_files: Mapping[str, Optional[bytes]],
) -> ManagedConfigPlan:
    """Return the exact remote changes for a KACE configuration deployment."""
    generated = generated_hardware.decode("utf-8")
    existing_root_bytes = remote_files.get(ROOT_REMOTE)
    existing_root = (existing_root_bytes or b"").decode("utf-8", errors="strict")
    # Klipper owns everything from the SAVE_CONFIG header through EOF.
    # Isolate it before section/include removal and newline normalization.
    save_config = ""
    save_config_match = _SAVE_CONFIG_RE.search(existing_root)
    if save_config_match:
        save_config = existing_root[save_config_match.start():]
        existing_root = existing_root[:save_config_match.start()]
    stale_legacy_macros = (
        _LEGACY_HEADER in existing_root
        and MANAGED_BEGIN not in existing_root
        and _has_include(existing_root, LEGACY_MACROS_REMOTE)
        and remote_files.get(LEGACY_MACROS_REMOTE) is None
    )
    if stale_legacy_macros:
        existing_root = _remove_include(existing_root, LEGACY_MACROS_REMOTE)
    # Previously migrated tuning lives in the managed hardware include.
    # Apply root values last so explicit user overrides keep their precedence.
    existing_hardware = (remote_files.get(HARDWARE_REMOTE) or b"").decode(
        "utf-8", errors="strict",
    )
    generated = _carry_user_tuning(generated, existing_hardware)
    generated = _carry_user_tuning(generated, existing_root)
    preserve_existing_macros = (
        remote_files.get(LEGACY_MACROS_REMOTE) is not None
        and _has_include(existing_root, LEGACY_MACROS_REMOTE)
    )
    effective_macros = None if preserve_existing_macros else generated_macros
    root, generated, migrated = _reconcile_root(
        existing_root, generated, effective_macros is not None, save_config,
        existing_hardware + "\n" + existing_root,
    )
    root += save_config

    artifacts = [
        PlannedConfigArtifact(ROOT_REMOTE, root.encode("utf-8"), existing_root_bytes),
        PlannedConfigArtifact(
            HARDWARE_REMOTE,
            generated.encode("utf-8"),
            remote_files.get(HARDWARE_REMOTE),
        ),
    ]
    if effective_macros is not None:
        artifacts.append(PlannedConfigArtifact(
            MACROS_REMOTE, effective_macros, remote_files.get(MACROS_REMOTE)
        ))

    existing_moonraker = remote_files.get(MOONRAKER_REMOTE)
    moonraker_text = (existing_moonraker or b"").decode("utf-8", errors="strict")
    reconciled_moonraker, changed = reconcile_moonraker_conf_content(moonraker_text)
    # Absence is not enough evidence that this config root owns Moonraker's
    # active file. Bootstrap creates it; deployments only reconcile a file
    # whose existence was positively observed.
    if changed and existing_moonraker is not None:
        if not reconciled_moonraker.endswith(("\n", "\r\n")):
            reconciled_moonraker += _newline(reconciled_moonraker)
        artifacts.append(PlannedConfigArtifact(
            MOONRAKER_REMOTE,
            reconciled_moonraker.encode("utf-8"),
            existing_moonraker,
        ))

    # Compare the effective destination, including sections migrated from the
    # user root. A retained setting must not be reported as lost just because
    # its section moved into the managed include.
    sources = tuple(remote_files.items())
    # Missing sources may be supplied by a pure planner's caller later. Live
    # semantic review always requires complete evidence (strict=True).
    final_hardware = effective_hardware_text(ManagedConfigPlan(tuple(artifacts), source_files=sources), strict=False)
    warnings = _setting_loss_warnings(ROOT_REMOTE, existing_root, final_hardware)
    warnings += _setting_loss_warnings(HARDWARE_REMOTE, existing_hardware, final_hardware)
    if effective_macros is not None and remote_files.get(MACROS_REMOTE) is not None:
        warnings += _setting_loss_warnings(
            MACROS_REMOTE, remote_files[MACROS_REMOTE].decode("utf-8", errors="strict"),
            effective_macros.decode("utf-8", errors="strict"),
        )
    if preserve_existing_macros and generated_macros is not None:
        warnings += (
            "Existing macros.cfg remains user-owned; generated starter macros were not deployed to avoid duplicate macro definitions.",
        )
    if stale_legacy_macros:
        warnings += (
            "Removed a stale legacy [include macros.cfg] after confirming that macros.cfg is absent.",
        )
    return ManagedConfigPlan(
        tuple(artifacts),
        legacy_migration=migrated,
        warnings=warnings,
        source_files=sources,
    )
