"""Plan KACE-owned configuration updates without mutating a live printer.

KACE owns generated files below ``kace/`` and one small include block in the
user's root ``printer.cfg``. Everything else remains user-owned. The planner is
pure: callers supply remote bytes and receive immutable artifacts plus a diff.
"""

from __future__ import annotations

import difflib
import re
from dataclasses import dataclass
from typing import Mapping, Optional

from core.reconciler import reconcile_moonraker_conf_content


HARDWARE_REMOTE = "kace/generated-hardware.cfg"
MACROS_REMOTE = "kace/generated-macros.cfg"
LEGACY_MACROS_REMOTE = "macros.cfg"
ROOT_REMOTE = "printer.cfg"
MOONRAKER_REMOTE = "moonraker.conf"
MANAGED_BEGIN = "# BEGIN KACE MANAGED: generated-includes"
MANAGED_END = "# END KACE MANAGED: generated-includes"

_SECTION_RE = re.compile(r"(?m)^\s*\[([^\]\r\n]+)\]\s*(?:[#;].*)?$")
_MANAGED_RE = re.compile(
    rf"(?ms)^\s*{re.escape(MANAGED_BEGIN)}\r?\n.*?^\s*{re.escape(MANAGED_END)}\s*(?:\r?\n)?"
)
_LEGACY_HEADER = "# This file was generated by KACE (Klipper Automated Configuration Ecosystem)"

# These are tuning values users commonly calibrate after initial generation.
# They are migrated into the KACE-owned hardware file instead of being reset.
_PRESERVED_OPTIONS = {
    "printer": {
        "max_velocity", "max_accel", "max_z_velocity", "max_z_accel",
        "square_corner_velocity", "minimum_cruise_ratio",
    },
    "extruder": {
        "control", "pid_kp", "pid_ki", "pid_kd", "pressure_advance",
        "pressure_advance_smooth_time", "nozzle_diameter", "filament_diameter",
    },
    "heater_bed": {"control", "pid_kp", "pid_ki", "pid_kd"},
    "force_move": {"enable_force_move"},
}
_PRESERVED_PREFIX_OPTIONS = {
    "stepper_": {"microsteps", "rotation_distance", "gear_ratio", "homing_speed"},
    "tmc": {"run_current", "hold_current", "stealthchop_threshold", "interpolate"},
}


@dataclass(frozen=True)
class PlannedConfigArtifact:
    remote_name: str
    content: bytes
    previous: Optional[bytes]

    @property
    def existed(self) -> bool:
        return self.previous is not None

    @property
    def changed(self) -> bool:
        return self.previous != self.content

    def unified_diff(self) -> str:
        before = (self.previous or b"").decode("utf-8", errors="replace").splitlines(True)
        after = self.content.decode("utf-8", errors="replace").splitlines(True)
        return "".join(difflib.unified_diff(
            before,
            after,
            fromfile=f"remote/{self.remote_name}",
            tofile=f"planned/{self.remote_name}",
            n=0,
        ))


@dataclass(frozen=True)
class ManagedConfigPlan:
    artifacts: tuple[PlannedConfigArtifact, ...]
    legacy_migration: bool = False
    warnings: tuple[str, ...] = ()

    @property
    def remote_names(self) -> tuple[str, ...]:
        return tuple(item.remote_name for item in self.artifacts)

    @property
    def changed_artifacts(self) -> tuple[PlannedConfigArtifact, ...]:
        return tuple(item for item in self.artifacts if item.changed)

    def dry_run_diff(self) -> str:
        return "\n".join(diff for item in self.artifacts if (diff := item.unified_diff()))


def _newline(text: str) -> str:
    return "\r\n" if "\r\n" in text else "\n"


def _section_spans(text: str):
    matches = list(_SECTION_RE.finditer(text))
    for index, match in enumerate(matches):
        yield (
            match.group(1).strip(),
            match.start(),
            matches[index + 1].start() if index + 1 < len(matches) else len(text),
        )


def _section_options(text: str) -> dict[str, dict[str, str]]:
    result: dict[str, dict[str, str]] = {}
    for name, start, end in _section_spans(text):
        options: dict[str, str] = {}
        header_end = text.find("\n", start, end)
        body = text[header_end + 1:end] if header_end >= 0 else ""
        for line in body.splitlines():
            if not line.strip() or line.lstrip().startswith(("#", ";")):
                continue
            match = re.match(r"^\s*([^:=#;]+?)\s*[:=]\s*(.*?)\s*(?:[#;].*)?$", line)
            if match:
                options[match.group(1).strip().casefold()] = match.group(2).strip()
        result[name.casefold()] = options
    return result


def _preserved_names(section: str) -> set[str]:
    folded = section.casefold()
    names = set(_PRESERVED_OPTIONS.get(folded, set()))
    for prefix, values in _PRESERVED_PREFIX_OPTIONS.items():
        if folded.startswith(prefix):
            names.update(values)
    return names


def _replace_or_insert_option(text: str, section: str, option: str, value: str) -> str:
    for name, start, end in _section_spans(text):
        if name.casefold() != section.casefold():
            continue
        body = text[start:end]
        pattern = re.compile(
            rf"(?mi)^(\s*{re.escape(option)}\s*[:=]\s*)([^#;\r\n]*?)(\s*)((?:[#;].*)?)$"
        )
        if pattern.search(body):
            replacement = pattern.sub(
                lambda m: f"{m.group(1)}{value}{m.group(3)}{m.group(4)}",
                body,
                count=1,
            )
        else:
            nl = _newline(text)
            replacement = body.rstrip("\r\n") + f"{nl}{option}: {value}{nl}"
        return text[:start] + replacement + text[end:]
    return text


def _carry_user_tuning(generated: str, existing_root: str) -> str:
    existing = _section_options(existing_root)
    generated_sections = {name.casefold() for name, _, _ in _section_spans(generated)}
    for section, options in existing.items():
        if section not in generated_sections:
            continue
        for option in _preserved_names(section):
            if option in options:
                generated = _replace_or_insert_option(generated, section, option, options[option])
    return generated


def _extract_generated_includes(generated: str) -> tuple[str, list[str]]:
    includes: list[str] = []
    spans = list(_section_spans(generated))
    for name, start, end in reversed(spans):
        if name.casefold().startswith("include "):
            includes.insert(0, f"[{name}]")
            generated = generated[:start] + generated[end:]
    return generated.strip() + "\n", includes


def _strip_owned_sections(root: str, owned_sections: set[str]) -> str:
    spans = list(_section_spans(root))
    for name, start, end in reversed(spans):
        folded = name.casefold()
        if folded.startswith("include "):
            continue
        if folded in owned_sections:
            root = root[:start] + root[end:]
    return root


def _managed_block(extra_includes: list[str], include_macros: bool, newline: str) -> str:
    lines = [MANAGED_BEGIN]
    lines.extend(extra_includes)
    lines.append(f"[include {HARDWARE_REMOTE}]")
    if include_macros:
        lines.append(f"[include {MACROS_REMOTE}]")
    lines.append(MANAGED_END)
    return newline.join(lines) + newline


def _has_include(text: str, remote_name: str) -> bool:
    wanted = f"include {remote_name}".casefold()
    return any(name.casefold() == wanted for name, _, _ in _section_spans(text))


def _remove_include(text: str, remote_name: str) -> str:
    wanted = f"include {remote_name}".casefold()
    for name, start, end in reversed(list(_section_spans(text))):
        if name.casefold() == wanted:
            text = text[:start] + text[end:]
    return text


def _reconcile_root(existing: str, generated: str, include_macros: bool) -> tuple[str, str, bool]:
    nl = _newline(existing or generated)
    generated, generated_includes = _extract_generated_includes(generated)
    owned = {name.casefold() for name, _, _ in _section_spans(generated)}
    migrated = _LEGACY_HEADER in existing and MANAGED_BEGIN not in existing

    begin_count = existing.count(MANAGED_BEGIN)
    end_count = existing.count(MANAGED_END)
    if begin_count != end_count or begin_count > 1:
        raise ValueError("printer.cfg contains malformed or duplicate KACE managed markers")

    if _MANAGED_RE.search(existing):
        base = _MANAGED_RE.sub("", existing, count=1)
    else:
        base = existing
    # Bootstrap and external tools may have reintroduced generated-owned
    # sections after KACE's marker block was created. Ownership is based on
    # section identity, not on whether the marker already existed.
    base = _strip_owned_sections(base, owned)

    # Do not duplicate an existing user-owned include. KACE only owns its
    # generated include entries; Mainsail/Fluidd and custom includes survive.
    existing_include_names = {
        name.casefold() for name, _, _ in _section_spans(base)
        if name.casefold().startswith("include ")
    }
    extra = [line for line in generated_includes if line[1:-1].casefold() not in existing_include_names]
    block = _managed_block(extra, include_macros, nl)
    base = base.lstrip("\r\n")
    reconciled = block + (nl if base else "") + base
    if not reconciled.endswith(nl):
        reconciled += nl
    return reconciled, generated, migrated


def build_managed_config_plan(
    generated_hardware: bytes,
    generated_macros: Optional[bytes],
    remote_files: Mapping[str, Optional[bytes]],
) -> ManagedConfigPlan:
    """Return the exact remote changes for a KACE configuration deployment."""
    generated = generated_hardware.decode("utf-8")
    existing_root_bytes = remote_files.get(ROOT_REMOTE)
    existing_root = (existing_root_bytes or b"").decode("utf-8", errors="strict")
    stale_legacy_macros = (
        _LEGACY_HEADER in existing_root
        and MANAGED_BEGIN not in existing_root
        and _has_include(existing_root, LEGACY_MACROS_REMOTE)
        and remote_files.get(LEGACY_MACROS_REMOTE) is None
    )
    if stale_legacy_macros:
        existing_root = _remove_include(existing_root, LEGACY_MACROS_REMOTE)
    generated = _carry_user_tuning(generated, existing_root)
    preserve_existing_macros = (
        remote_files.get(LEGACY_MACROS_REMOTE) is not None
        and _has_include(existing_root, LEGACY_MACROS_REMOTE)
    )
    effective_macros = None if preserve_existing_macros else generated_macros
    root, generated, migrated = _reconcile_root(
        existing_root, generated, effective_macros is not None
    )

    artifacts = [
        PlannedConfigArtifact(ROOT_REMOTE, root.encode("utf-8"), existing_root_bytes),
        PlannedConfigArtifact(
            HARDWARE_REMOTE,
            generated.encode("utf-8"),
            remote_files.get(HARDWARE_REMOTE),
        ),
    ]
    if effective_macros is not None:
        artifacts.append(PlannedConfigArtifact(
            MACROS_REMOTE, effective_macros, remote_files.get(MACROS_REMOTE)
        ))

    existing_moonraker = remote_files.get(MOONRAKER_REMOTE)
    moonraker_text = (existing_moonraker or b"").decode("utf-8", errors="strict")
    reconciled_moonraker, changed = reconcile_moonraker_conf_content(moonraker_text)
    # Absence is not enough evidence that this config root owns Moonraker's
    # active file. Bootstrap creates it; deployments only reconcile a file
    # whose existence was positively observed.
    if changed and existing_moonraker is not None:
        if not reconciled_moonraker.endswith(("\n", "\r\n")):
            reconciled_moonraker += _newline(reconciled_moonraker)
        artifacts.append(PlannedConfigArtifact(
            MOONRAKER_REMOTE,
            reconciled_moonraker.encode("utf-8"),
            existing_moonraker,
        ))

    warnings: tuple[str, ...] = ()
    if preserve_existing_macros and generated_macros is not None:
        warnings += (
            "Existing macros.cfg remains user-owned; generated starter macros were not deployed to avoid duplicate macro definitions.",
        )
    if stale_legacy_macros:
        warnings += (
            "Removed a stale legacy [include macros.cfg] after confirming that macros.cfg is absent.",
        )
    return ManagedConfigPlan(
        tuple(artifacts),
        legacy_migration=migrated,
        warnings=warnings,
    )
