#!/usr/bin/env python3
"""Generate representative KACE configs and validate them with pinned Klipper."""

from __future__ import annotations

import argparse
from dataclasses import asdict
import json
from pathlib import Path
import shutil
import subprocess
import sys
import time

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from tests.matrix.cases import (
    FACTOR_VALUES, build_cases, generate_case, pair_tokens,
    pairwise_rows, supported_boards,
)


KLIPPER_REF = "d865997403cad36d105026f73a4b76dcacec4c76"
SCHEMA_VERSION = 1
FINAL_PASS = "PASS"
FINAL_EXPECTED_REJECT = "EXPECTED_REJECT"
FINAL_KACE_ERROR = "KACE_ERROR"
FINAL_KLIPPER_ERROR = "KLIPPER_ERROR"
FINAL_INFRA_ERROR = "INFRA_ERROR"
_pair_tokens = pair_tokens  # Backward-compatible test helper name.


def _run(command: list[str], cwd: Path) -> subprocess.CompletedProcess:
    return subprocess.run(command, cwd=cwd, text=True, encoding="utf-8", errors="replace",
                          capture_output=True, check=False)


def run_docker_validation(artifact_dir: Path, manifest_path: Path) -> tuple[dict, str | None]:
    docker = shutil.which("docker")
    if docker is None:
        return {}, "Docker CLI is not installed or not in PATH"
    image = f"kace-klipper-matrix:{KLIPPER_REF[:12]}"
    build = _run([docker, "build", "--build-arg", f"KLIPPER_REF={KLIPPER_REF}",
                  "-f", "tests/matrix/Dockerfile", "-t", image, "."], PROJECT_ROOT)
    if build.returncode != 0:
        return {}, f"Docker build failed: {(build.stderr or build.stdout).strip()}"
    result_name = "klipper-results.json"
    validation = _run([
        docker, "run", "--rm", "--network", "none",
        "--mount", f"type=bind,source={artifact_dir.resolve()},target=/matrix",
        "-e", f"KLIPPER_REF={KLIPPER_REF}", image,
        f"/matrix/{manifest_path.name}", f"/matrix/{result_name}",
    ], PROJECT_ROOT)
    if validation.returncode != 0:
        return {}, f"Docker validation failed: {(validation.stderr or validation.stdout).strip()}"
    try:
        payload = json.loads((artifact_dir / result_name).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return {}, f"Invalid Docker result: {exc}"
    if payload.get("klipper_ref") != KLIPPER_REF:
        return {}, "Docker result reported a different Klipper commit"
    return payload.get("results", {}), None


def classify(generation: dict, klipper: dict | None, infra_error: str | None) -> tuple[str, str]:
    if generation["status"] == "expected_reject":
        return FINAL_EXPECTED_REJECT, generation["reason"]
    if generation["status"] in {"kace_error", "unexpected_generation"}:
        return FINAL_KACE_ERROR, generation["reason"]
    if infra_error:
        return FINAL_INFRA_ERROR, infra_error
    if not klipper or not klipper.get("valid"):
        return FINAL_KLIPPER_ERROR, (klipper or {}).get("reason", "Klipper returned no result")
    return FINAL_PASS, klipper["reason"]


def _report(payload: dict) -> str:
    summary = payload["summary"]
    lines = ["# KACE configuration validation matrix", "",
             f"- Profile: `{payload['profile']}`", f"- Klipper commit: `{payload['klipper_ref']}`",
             f"- Total combinations: **{summary['total']}**",
             f"- Generated by KACE: **{summary['generated']}**", f"- PASS: **{summary.get(FINAL_PASS, 0)}**",
             f"- Expected safe rejections: **{summary.get(FINAL_EXPECTED_REJECT, 0)}**",
             f"- KACE errors: **{summary.get(FINAL_KACE_ERROR, 0)}**",
             f"- Klipper validation errors: **{summary.get(FINAL_KLIPPER_ERROR, 0)}**",
             f"- Infrastructure errors: **{summary.get(FINAL_INFRA_ERROR, 0)}**",
             f"- Duration: **{payload['duration_seconds']:.3f}s**", "", "## Coverage", "",
             f"- Boards: {', '.join(payload['coverage']['boards'])}",
             f"- MCUs: {', '.join(payload['coverage']['mcus'])}",
             f"- Kinematics: {', '.join(payload['coverage']['kinematics'])}",
             f"- Probes: {', '.join(payload['coverage']['probes'])}", "", "## Results", "",
             "| ID | Board / MCU | Factors | Result | Reason |", "|---|---|---|---|---|"]
    for case in payload["cases"]:
        spec = case["spec"]
        factors = f"{spec['kinematics']}; {spec['bed']}; {spec['homing']}; {spec['probe']}; display={spec['display']}"
        reason = case["reason"].replace("|", "\\|").replace("\n", " ")
        lines.append(f"| `{case['id']}` | {spec['board']} / {spec['mcu']} | {factors} | "
                     f"**{case['result']}** | {reason} |")
    return "\n".join(lines) + "\n"


def execute(profile: str, artifact_dir: Path, skip_docker: bool = False) -> dict:
    started = time.monotonic()
    config_dir = artifact_dir / "configs"
    config_dir.mkdir(parents=True, exist_ok=True)
    cases = [{"id": spec.case_id, "spec": asdict(spec),
              "config_path": f"configs/{spec.case_id}.cfg",
              "generation": generate_case(spec, config_dir)} for spec in build_cases(profile)]
    manifest = {"schema_version": SCHEMA_VERSION, "profile": profile,
                "klipper_ref": KLIPPER_REF, "cases": cases}
    manifest_path = artifact_dir / "manifest.generated.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    klipper_results, infra_error = ({}, "Docker validation explicitly skipped") if skip_docker \
        else run_docker_validation(artifact_dir, manifest_path)
    for case in cases:
        case["klipper"] = klipper_results.get(case["id"])
        case["result"], case["reason"] = classify(case["generation"], case["klipper"], infra_error)
    summary = {name: sum(case["result"] == name for case in cases) for name in
               (FINAL_PASS, FINAL_EXPECTED_REJECT, FINAL_KACE_ERROR, FINAL_KLIPPER_ERROR, FINAL_INFRA_ERROR)}
    summary.update(total=len(cases), generated=sum(c["generation"]["status"] == "generated" for c in cases))
    coverage = {key: sorted({case["spec"][field] for case in cases}) for key, field in
                (("boards", "board"), ("mcus", "mcu"), ("kinematics", "kinematics"), ("probes", "probe"))}
    payload = {**manifest, "cases": cases, "summary": summary, "coverage": coverage,
               "duration_seconds": round(time.monotonic() - started, 6),
               "infrastructure_error": infra_error}
    (artifact_dir / "report.json").write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    (artifact_dir / "report.md").write_text(_report(payload), encoding="utf-8")
    return payload


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--profile", choices=("quick", "full"), default="quick")
    parser.add_argument("--artifacts", type=Path, default=PROJECT_ROOT / "tests/matrix/artifacts")
    parser.add_argument("--skip-docker", action="store_true", help="Generate only; results are INFRA_ERROR")
    args = parser.parse_args()
    payload = execute(args.profile, args.artifacts, args.skip_docker)
    print(_report(payload))
    failures = sum(payload["summary"][key] for key in
                   (FINAL_KACE_ERROR, FINAL_KLIPPER_ERROR, FINAL_INFRA_ERROR))
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
