import unittest

from core.managed_config import (
    HARDWARE_REMOTE,
    LEGACY_MACROS_REMOTE,
    MACROS_REMOTE,
    MANAGED_BEGIN,
    ROOT_REMOTE,
    build_managed_config_plan,
)


GENERATED = b"""# This file was generated by KACE (Klipper Automated Configuration Ecosystem)
[include mainsail.cfg]
[mcu]
serial: /dev/serial/by-id/test
[printer]
kinematics: cartesian
max_velocity: 300
[force_move]
enable_force_move: True
[extruder]
control: pid
pid_Kp: 22.2
pid_Ki: 1.0
pid_Kd: 100
"""


class TestManagedConfigPlan(unittest.TestCase):
    def test_save_config_after_managed_section_is_preserved_exactly(self):
        saved = (
            b"#*# <---------------------- SAVE_CONFIG ---------------------->\n"
            b"#*# DO NOT EDIT THIS BLOCK OR BELOW. The contents are auto-generated.\n"
            b"#*#\n"
            b"#*# [bltouch]\n"
            b"#*# z_offset = 2.375  \n"
            b"#*#\n"
            b"#*# [bed_mesh default]\n"
            b"#*# points =\n"
            b"#*#     0.015, -0.025, 0.035\n"
        )
        for newline in (b"\n", b"\r\n"):
            for ending in (b"", newline, newline * 2):
                with self.subTest(newline=newline, ending=ending):
                    block = saved.rstrip(b"\n").replace(b"\n", newline) + ending
                    existing = b"[mcu]" + newline + b"serial: old" + newline + block
                    first = build_managed_config_plan(GENERATED, None, {ROOT_REMOTE: existing})
                    files = {item.remote_name: item.content for item in first.artifacts}
                    root = files[ROOT_REMOTE]
                    self.assertEqual(root[root.index(b"#*# <"):], block)
                    self.assertEqual(root.count(b"SAVE_CONFIG"), 1)
                    self.assertNotIn(b"serial: old", root)
                    self.assertNotIn(b"#*#", files[HARDWARE_REMOTE])
                    self.assertIn(b"serial: /dev/serial/by-id/test", files[HARDWARE_REMOTE])

                    second = build_managed_config_plan(GENERATED, None, files)
                    self.assertEqual(
                        files, {item.remote_name: item.content for item in second.artifacts},
                    )
                    self.assertEqual(second.changed_artifacts, ())

                    generated = GENERATED.replace(b"/dev/serial/by-id/test", b"/dev/serial/by-id/new")
                    updated = build_managed_config_plan(generated, None, files)
                    updated_files = {item.remote_name: item.content for item in updated.artifacts}
                    self.assertEqual(updated_files[ROOT_REMOTE], root)
                    self.assertIn(b"serial: /dev/serial/by-id/new", updated_files[HARDWARE_REMOTE])
                    self.assertEqual(
                        [item.remote_name for item in updated.changed_artifacts], [HARDWARE_REMOTE],
                    )

    def test_save_config_survives_removal_of_stale_legacy_include(self):
        saved = (
            b"#*# <---------------------- SAVE_CONFIG ---------------------->\n"
            b"#*# DO NOT EDIT THIS BLOCK OR BELOW. The contents are auto-generated.\n"
            b"#*#\n#*# [probe]\n#*# z_offset = 1.725\n"
        )
        existing = GENERATED + b"[include macros.cfg]\n" + saved
        first = build_managed_config_plan(
            GENERATED, b"# macros\n", {ROOT_REMOTE: existing, LEGACY_MACROS_REMOTE: None},
        )
        files = {item.remote_name: item.content for item in first.artifacts}
        root = files[ROOT_REMOTE]
        self.assertEqual(root[root.index(b"#*# <"):], saved)
        self.assertNotIn(b"[include macros.cfg]", root)
        self.assertIn(MACROS_REMOTE.encode(), root)
        self.assertEqual(
            build_managed_config_plan(GENERATED, b"# macros\n", files).changed_artifacts, (),
        )

    def test_save_config_after_user_section_keeps_exact_eof(self):
        saved = (
            b"#*# <---------------------- SAVE_CONFIG ---------------------->\n"
            b"#*# DO NOT EDIT THIS BLOCK OR BELOW. The contents are auto-generated.\n"
            b"#*#\n#*# [probe]\n#*# z_offset = 1.725"
        )
        user = b"[gcode_macro USER]\ngcode: M117 keep\n"
        first = build_managed_config_plan(GENERATED, None, {ROOT_REMOTE: user + saved})
        files = {item.remote_name: item.content for item in first.artifacts}
        self.assertTrue(files[ROOT_REMOTE].endswith(user + saved))
        self.assertEqual(build_managed_config_plan(GENERATED, None, files).changed_artifacts, ())

    def test_preserves_user_sections_includes_pid_and_force_move_choice(self):
        existing = b"""[include user-extra.cfg]
[extruder]
control: pid
pid_Kp: 31.5
pid_Ki: 2.2
pid_Kd: 140
[force_move]
enable_force_move: False
[gcode_macro USER_MACRO]
gcode:
    M117 user
"""
        plan = build_managed_config_plan(
            GENERATED,
            b"[gcode_macro KACE_TEST]\ngcode: G28\n",
            {ROOT_REMOTE: existing, HARDWARE_REMOTE: None, MACROS_REMOTE: None, "moonraker.conf": None},
        )
        files = {item.remote_name: item.content for item in plan.artifacts}
        root = files[ROOT_REMOTE].decode()
        hardware = files[HARDWARE_REMOTE].decode()

        self.assertIn(MANAGED_BEGIN, root)
        self.assertIn("[include user-extra.cfg]", root)
        self.assertIn("[gcode_macro USER_MACRO]", root)
        self.assertIn("[extruder]", root)
        self.assertNotIn("[force_move]", root)
        self.assertIn("pid_Kp: 31.5", root)
        self.assertNotIn("pid_Kp:", hardware)
        self.assertIn("enable_force_move: False", hardware)
        self.assertIn(MACROS_REMOTE, root)

        second = build_managed_config_plan(
            GENERATED, b"[gcode_macro KACE_TEST]\ngcode: G28\n", files,
        )
        self.assertEqual(files, {item.remote_name: item.content for item in second.artifacts})
        self.assertEqual(second.changed_artifacts, ())

    def test_repeated_deployments_preserve_motion_and_driver_tuning(self):
        cases = (
            ("printer", "max_velocity: 300\nmax_accel: 3000", "max_velocity: 80\nmax_accel: 1200"),
            ("extruder", "pressure_advance: 0", "pressure_advance: 0.045"),
            ("heater_bed", "control: pid\npid_Kp: 20\npid_Ki: 1\npid_Kd: 100",
             "control: pid\npid_Kp: 33\npid_Ki: 2\npid_Kd: 140"),
            ("stepper_x", "rotation_distance: 40\nmicrosteps: 16",
             "rotation_distance: 39.8\nmicrosteps: 32\ngear_ratio: 2:1\nhoming_speed: 25"),
            ("tmc2209 stepper_x", "run_current: 0.8\ninterpolate: True",
             "run_current: 0.65\nhold_current: 0.3\ninterpolate: False"),
        )
        for section, defaults, tuning in cases:
            with self.subTest(section=section):
                generated = f"[{section}]\n{defaults}\n".encode()
                remote = {ROOT_REMOTE: f"[{section}]\n{tuning}\n".encode()}
                first = build_managed_config_plan(generated, None, remote)
                files = {item.remote_name: item.content for item in first.artifacts}
                for option in tuning.splitlines():
                    self.assertIn(option.encode(), files[ROOT_REMOTE] if section == "heater_bed" else files[HARDWARE_REMOTE])
                second = build_managed_config_plan(generated, None, files)
                self.assertEqual(
                    files, {item.remote_name: item.content for item in second.artifacts},
                )
                self.assertEqual(second.changed_artifacts, ())

    def test_root_tuning_takes_precedence_without_losing_other_managed_values(self):
        managed = GENERATED.replace(b"pid_Kp: 22.2", b"pid_Kp: 30").replace(
            b"pid_Ki: 1.0", b"pid_Ki: 2.2",
        )
        remote = {
            ROOT_REMOTE: b"[extruder]\npid_Kp: 31.5\n",
            HARDWARE_REMOTE: managed,
        }
        original = dict(remote)
        plan = build_managed_config_plan(GENERATED, None, remote)
        files = {item.remote_name: item.content for item in plan.artifacts}
        self.assertIn(b"pid_Kp: 31.5", files[ROOT_REMOTE])
        self.assertIn(b"pid_Ki: 2.2", files[ROOT_REMOTE])
        self.assertEqual(remote, original)
        second = build_managed_config_plan(GENERATED, None, files)
        self.assertEqual(second.changed_artifacts, ())

    def test_generated_fields_update_while_migrated_tuning_is_preserved(self):
        first = build_managed_config_plan(
            GENERATED, None,
            {ROOT_REMOTE: b"[printer]\nmax_velocity: 80\n[extruder]\npid_Kp: 33\n"},
        )
        remote = {item.remote_name: item.content for item in first.artifacts}
        generated = GENERATED.replace(b"/dev/serial/by-id/test", b"/dev/serial/by-id/new").replace(
            b"kinematics: cartesian", b"kinematics: corexy",
        ) + b"[fan]\npin: PA8\n"
        second = build_managed_config_plan(generated, None, remote)
        files = {item.remote_name: item.content for item in second.artifacts}
        hardware = files[HARDWARE_REMOTE]
        self.assertIn(b"serial: /dev/serial/by-id/new", hardware)
        self.assertIn(b"kinematics: corexy", hardware)
        self.assertIn(b"[fan]\npin: PA8", hardware)
        self.assertIn(b"max_velocity: 80", hardware)
        self.assertIn(b"pid_Kp: 33", files[ROOT_REMOTE])
        self.assertEqual([item.remote_name for item in second.changed_artifacts], [HARDWARE_REMOTE])
        self.assertEqual(build_managed_config_plan(generated, None, files).changed_artifacts, ())

    def test_missing_or_empty_previous_hardware_uses_generated_values(self):
        for previous in ({}, {HARDWARE_REMOTE: None}, {HARDWARE_REMOTE: b""}):
            with self.subTest(previous=previous):
                first = build_managed_config_plan(GENERATED, None, previous)
                files = {item.remote_name: item.content for item in first.artifacts}
                self.assertIn(b"max_velocity: 300", files[ROOT_REMOTE])
                self.assertIn(b"pid_Kp: 22.2", files[ROOT_REMOTE])
                self.assertIn(b"enable_force_move: True", files[ROOT_REMOTE])
                self.assertEqual(build_managed_config_plan(GENERATED, None, files).changed_artifacts, ())

    def test_invalid_previous_hardware_encoding_prevents_replacement(self):
        with self.assertRaises(UnicodeDecodeError):
            build_managed_config_plan(GENERATED, None, {HARDWARE_REMOTE: b"\xff"})

    def test_watermark_control_does_not_restore_old_pid_tuning(self):
        generated = GENERATED.replace(
            b"control: pid\npid_Kp: 22.2\npid_Ki: 1.0\npid_Kd: 100\n",
            b"control: watermark\n",
        )
        existing = b"""[extruder]
control: pid
pid_Kp: 31.5
pid_Ki: 2.2
pid_Kd: 140
"""
        plan = build_managed_config_plan(
            generated,
            None,
            {ROOT_REMOTE: existing, HARDWARE_REMOTE: None, "moonraker.conf": None},
        )
        hardware = next(
            item.content.decode() for item in plan.artifacts if item.remote_name == HARDWARE_REMOTE
        )
        root = next(item.content.decode() for item in plan.artifacts if item.remote_name == ROOT_REMOTE)
        self.assertIn("control: watermark", root)
        self.assertNotIn("control:", hardware)
        self.assertNotIn("pid_Kp", hardware)
        self.assertNotIn("pid_Ki", hardware)
        self.assertNotIn("pid_Kd", hardware)

    def test_watermark_control_does_not_restore_managed_pid_tuning(self):
        first = build_managed_config_plan(GENERATED, None, {ROOT_REMOTE: GENERATED})
        remote = {item.remote_name: item.content for item in first.artifacts}
        generated = GENERATED.replace(
            b"control: pid\npid_Kp: 22.2\npid_Ki: 1.0\npid_Kd: 100\n",
            b"control: watermark\n",
        )
        plan = build_managed_config_plan(generated, None, remote)
        files = {item.remote_name: item.content for item in plan.artifacts}
        self.assertIn(b"control: watermark", files[ROOT_REMOTE])
        self.assertNotIn(b"pid_", files[HARDWARE_REMOTE])
        self.assertEqual(build_managed_config_plan(generated, None, files).changed_artifacts, ())

    def test_reconciliation_is_idempotent(self):
        first = build_managed_config_plan(
            GENERATED, b"# macros\n", {name: None for name in (
                ROOT_REMOTE, HARDWARE_REMOTE, MACROS_REMOTE, "moonraker.conf"
            )}
        )
        remote = {item.remote_name: item.content for item in first.artifacts}
        remote["moonraker.conf"] = None
        second = build_managed_config_plan(GENERATED, b"# macros\n", remote)
        self.assertEqual(
            {item.remote_name: item.content for item in first.artifacts},
            {item.remote_name: item.content for item in second.artifacts},
        )

    def test_legacy_full_generated_file_has_migration_path(self):
        legacy = GENERATED + b"\n[gcode_macro USER_ADDITION]\ngcode: M117 kept\n"
        plan = build_managed_config_plan(
            GENERATED, None,
            {ROOT_REMOTE: legacy, HARDWARE_REMOTE: None, MACROS_REMOTE: None, "moonraker.conf": None},
        )
        root = next(item.content for item in plan.artifacts if item.remote_name == ROOT_REMOTE).decode()
        self.assertTrue(plan.legacy_migration)
        self.assertIn("[gcode_macro USER_ADDITION]", root)
        self.assertEqual(root.count("[mcu]"), 0)
        self.assertIn(HARDWARE_REMOTE, root)

    def test_dry_run_diff_names_every_changed_file(self):
        plan = build_managed_config_plan(
            GENERATED, None,
            {ROOT_REMOTE: b"# user\n", HARDWARE_REMOTE: None, MACROS_REMOTE: None, "moonraker.conf": None},
        )
        diff = plan.dry_run_diff()
        self.assertIn("remote/printer.cfg", diff)
        self.assertIn("planned/kace/generated-hardware.cfg", diff)

    def test_duplicate_managed_markers_fail_closed(self):
        root = (
            f"{MANAGED_BEGIN}\n[include {HARDWARE_REMOTE}]\n# END KACE MANAGED: generated-includes\n"
            f"{MANAGED_BEGIN}\n[include {HARDWARE_REMOTE}]\n# END KACE MANAGED: generated-includes\n"
        ).encode()
        with self.assertRaisesRegex(ValueError, "duplicate"):
            build_managed_config_plan(
                GENERATED, None,
                {ROOT_REMOTE: root, HARDWARE_REMOTE: None, MACROS_REMOTE: None, "moonraker.conf": None},
            )

    def test_existing_legacy_macros_are_preserved_without_duplicate_include(self):
        root = GENERATED + b"\n[include macros.cfg]\n"
        plan = build_managed_config_plan(
            GENERATED,
            b"[gcode_macro GENERATED]\ngcode: G28\n",
            {
                ROOT_REMOTE: root,
                HARDWARE_REMOTE: None,
                MACROS_REMOTE: None,
                LEGACY_MACROS_REMOTE: b"[gcode_macro USER]\ngcode: M117 keep\n",
                "moonraker.conf": None,
            },
        )
        files = {item.remote_name: item.content for item in plan.artifacts}
        reconciled_root = files[ROOT_REMOTE].decode()
        self.assertIn("[include macros.cfg]", reconciled_root)
        self.assertNotIn(MACROS_REMOTE, reconciled_root)
        self.assertNotIn(MACROS_REMOTE, files)
        self.assertTrue(plan.warnings)

    def test_missing_legacy_macros_include_is_replaced_by_managed_macros(self):
        root = GENERATED + b"\n[include macros.cfg]\n"
        plan = build_managed_config_plan(
            GENERATED,
            b"[gcode_macro GENERATED]\ngcode: G28\n",
            {
                ROOT_REMOTE: root,
                HARDWARE_REMOTE: None,
                MACROS_REMOTE: None,
                LEGACY_MACROS_REMOTE: None,
                "moonraker.conf": None,
            },
        )
        files = {item.remote_name: item.content for item in plan.artifacts}
        reconciled_root = files[ROOT_REMOTE].decode()
        self.assertNotIn("[include macros.cfg]", reconciled_root)
        self.assertIn(MACROS_REMOTE, reconciled_root)
        self.assertIn(MACROS_REMOTE, files)


if __name__ == "__main__":
    unittest.main()
