import unittest

from core.managed_config import (
    HARDWARE_REMOTE,
    LEGACY_MACROS_REMOTE,
    MACROS_REMOTE,
    MANAGED_BEGIN,
    ROOT_REMOTE,
    build_managed_config_plan,
)


GENERATED = b"""# This file was generated by KACE (Klipper Automated Configuration Ecosystem)
[include mainsail.cfg]
[mcu]
serial: /dev/serial/by-id/test
[printer]
kinematics: cartesian
max_velocity: 300
[force_move]
enable_force_move: True
[extruder]
control: pid
pid_Kp: 22.2
pid_Ki: 1.0
pid_Kd: 100
"""


class TestManagedConfigPlan(unittest.TestCase):
    def test_preserves_user_sections_includes_pid_and_force_move_choice(self):
        existing = b"""[include user-extra.cfg]
[extruder]
control: pid
pid_Kp: 31.5
pid_Ki: 2.2
pid_Kd: 140
[force_move]
enable_force_move: False
[gcode_macro USER_MACRO]
gcode:
    M117 user
"""
        plan = build_managed_config_plan(
            GENERATED,
            b"[gcode_macro KACE_TEST]\ngcode: G28\n",
            {ROOT_REMOTE: existing, HARDWARE_REMOTE: None, MACROS_REMOTE: None, "moonraker.conf": None},
        )
        files = {item.remote_name: item.content for item in plan.artifacts}
        root = files[ROOT_REMOTE].decode()
        hardware = files[HARDWARE_REMOTE].decode()

        self.assertIn(MANAGED_BEGIN, root)
        self.assertIn("[include user-extra.cfg]", root)
        self.assertIn("[gcode_macro USER_MACRO]", root)
        self.assertNotIn("[extruder]", root)
        self.assertNotIn("[force_move]", root)
        self.assertIn("pid_Kp: 31.5", hardware)
        self.assertIn("enable_force_move: False", hardware)
        self.assertIn(MACROS_REMOTE, root)

    def test_reconciliation_is_idempotent(self):
        first = build_managed_config_plan(
            GENERATED, b"# macros\n", {name: None for name in (
                ROOT_REMOTE, HARDWARE_REMOTE, MACROS_REMOTE, "moonraker.conf"
            )}
        )
        remote = {item.remote_name: item.content for item in first.artifacts}
        remote["moonraker.conf"] = None
        second = build_managed_config_plan(GENERATED, b"# macros\n", remote)
        self.assertEqual(
            {item.remote_name: item.content for item in first.artifacts},
            {item.remote_name: item.content for item in second.artifacts},
        )

    def test_legacy_full_generated_file_has_migration_path(self):
        legacy = GENERATED + b"\n[gcode_macro USER_ADDITION]\ngcode: M117 kept\n"
        plan = build_managed_config_plan(
            GENERATED, None,
            {ROOT_REMOTE: legacy, HARDWARE_REMOTE: None, MACROS_REMOTE: None, "moonraker.conf": None},
        )
        root = next(item.content for item in plan.artifacts if item.remote_name == ROOT_REMOTE).decode()
        self.assertTrue(plan.legacy_migration)
        self.assertIn("[gcode_macro USER_ADDITION]", root)
        self.assertEqual(root.count("[mcu]"), 0)
        self.assertIn(HARDWARE_REMOTE, root)

    def test_dry_run_diff_names_every_changed_file(self):
        plan = build_managed_config_plan(
            GENERATED, None,
            {ROOT_REMOTE: b"# user\n", HARDWARE_REMOTE: None, MACROS_REMOTE: None, "moonraker.conf": None},
        )
        diff = plan.dry_run_diff()
        self.assertIn("remote/printer.cfg", diff)
        self.assertIn("planned/kace/generated-hardware.cfg", diff)

    def test_duplicate_managed_markers_fail_closed(self):
        root = (
            f"{MANAGED_BEGIN}\n[include {HARDWARE_REMOTE}]\n# END KACE MANAGED: generated-includes\n"
            f"{MANAGED_BEGIN}\n[include {HARDWARE_REMOTE}]\n# END KACE MANAGED: generated-includes\n"
        ).encode()
        with self.assertRaisesRegex(ValueError, "duplicate"):
            build_managed_config_plan(
                GENERATED, None,
                {ROOT_REMOTE: root, HARDWARE_REMOTE: None, MACROS_REMOTE: None, "moonraker.conf": None},
            )

    def test_existing_legacy_macros_are_preserved_without_duplicate_include(self):
        root = GENERATED + b"\n[include macros.cfg]\n"
        plan = build_managed_config_plan(
            GENERATED,
            b"[gcode_macro GENERATED]\ngcode: G28\n",
            {
                ROOT_REMOTE: root,
                HARDWARE_REMOTE: None,
                MACROS_REMOTE: None,
                LEGACY_MACROS_REMOTE: b"[gcode_macro USER]\ngcode: M117 keep\n",
                "moonraker.conf": None,
            },
        )
        files = {item.remote_name: item.content for item in plan.artifacts}
        reconciled_root = files[ROOT_REMOTE].decode()
        self.assertIn("[include macros.cfg]", reconciled_root)
        self.assertNotIn(MACROS_REMOTE, reconciled_root)
        self.assertNotIn(MACROS_REMOTE, files)
        self.assertTrue(plan.warnings)

    def test_missing_legacy_macros_include_is_replaced_by_managed_macros(self):
        root = GENERATED + b"\n[include macros.cfg]\n"
        plan = build_managed_config_plan(
            GENERATED,
            b"[gcode_macro GENERATED]\ngcode: G28\n",
            {
                ROOT_REMOTE: root,
                HARDWARE_REMOTE: None,
                MACROS_REMOTE: None,
                LEGACY_MACROS_REMOTE: None,
                "moonraker.conf": None,
            },
        )
        files = {item.remote_name: item.content for item in plan.artifacts}
        reconciled_root = files[ROOT_REMOTE].decode()
        self.assertNotIn("[include macros.cfg]", reconciled_root)
        self.assertIn(MACROS_REMOTE, reconciled_root)
        self.assertIn(MACROS_REMOTE, files)


if __name__ == "__main__":
    unittest.main()
