"""
tests/unit/test_pin_validator.py
================================
Tests for the pre-flight config validation that prevents a malformed
printer.cfg from being pushed to a low-RAM Pi.

Background
----------
The bug that motivated this: a generated printer.cfg containing only the
Mainsail client macro body (no [mcu], no [printer], no steppers) was
uploaded to a Raspberry Pi 3. Klipper fatal'd with
"Option 'serial' in section 'mcu' must be specified", systemd restart-
looped it, and the 1 GB Pi OOM-killed sshd/networking — total lockout.

validate_required_sections() catches that class of defect before upload.
validate_pins_for_mcu() catches cross-family pin-namespace mixes
(e.g. STM32 'PD7' pins on an LPC1769 board).
"""

import os
import unittest
from unittest.mock import patch, mock_open, MagicMock

from core.pin_validator import (
    validate_required_sections,
    validate_pins_for_mcu,
    arch_for_mcu,
)
from core.deployer import _preflight_check


# ── Fixtures as multi-line strings ──────────────────────────────────

# Exactly the kind of broken config seen in klippy.log: only Mainsail macros,
# NO [mcu] / [printer] / steppers. Must be rejected.
MACROS_ONLY_CFG = """\
# This file was generated by KACE
[include mainsail.cfg]
[include macros.cfg]

[virtual_sdcard]
path = ~/printer_data/gcodes

[pause_resume]
[display_status]
[respond]

[gcode_macro CANCEL_PRINT]
rename_existing = CANCEL_PRINT_BASE
gcode = CANCEL_PRINT_BASE
"""

# A structurally valid config covering all required sections.
VALID_CFG = """\
[mcu]
serial: /dev/serial/by-id/usb-Klipper_lpc1769_xxx-if00

[printer]
kinematics: cartesian
max_velocity: 300

[stepper_x]
step_pin: P1.4
dir_pin: !P1.8
endstop_pin: ^P1.27
microsteps: 16
rotation_distance: 32

[extruder]
step_pin: P1.15
nozzle_diameter: 0.4
heater_pin: P2.7
sensor_pin: P0.23
sensor_type: Generic 3950
"""

# Valid structure but STM32 pins on an LPC1769 board (the cross-family mix).
MIXED_PIN_CFG = """\
[mcu]
serial: /dev/serial/by-id/usb-Klipper_lpc1769_xxx-if00

[printer]
kinematics: cartesian

[stepper_x]
step_pin: PD7
dir_pin: !PC5
endstop_pin: ^PC2
microsteps: 16

[stepper_z1]
step_pin: P1.15
dir_pin: P1.14
"""


class TestValidateRequiredSections(unittest.TestCase):
    """Structural integrity: every deployable config needs [mcu]+serial, [printer], a stepper."""

    def _run(self, content):
        with patch("builtins.open", mock_open(read_data=content)):
            return validate_required_sections("/fake/path/printer.cfg")

    def test_macros_only_config_is_rejected(self):
        """The exact failure from klippy.log — only Mainsail macros, no hardware body."""
        problems = self._run(MACROS_ONLY_CFG)
        self.assertIsNotNone(problems)
        # Must flag at least: missing [mcu], missing [printer], missing stepper.
        joined = " ".join(problems)
        self.assertIn("[mcu]", joined)
        self.assertIn("[printer]", joined)
        self.assertIn("stepper", joined)

    def test_valid_config_has_no_problems(self):
        problems = self._run(VALID_CFG)
        self.assertEqual(problems, [])

    def test_mcu_present_but_no_serial_is_caught(self):
        """[mcu] without serial: is the precise fatal error from the log."""
        broken = "[mcu]\n[printer]\nkinematics: corexy\n[stepper_x]\nstep_pin: P1.4\n"
        problems = self._run(broken)
        self.assertIsNotNone(problems)
        self.assertTrue(
            any("serial" in p for p in problems),
            f"Expected a missing-serial problem, got: {problems}",
        )

    def test_unreadable_file_returns_none(self):
        with patch("builtins.open", side_effect=OSError("disk error")):
            self.assertIsNone(validate_required_sections("/nope"))


class TestValidatePinsForMcu(unittest.TestCase):
    """Cross-family pin-namespace detection."""

    def _run(self, content, mcu):
        with patch("builtins.open", mock_open(read_data=content)):
            return validate_pins_for_mcu("/fake/path/printer.cfg", mcu)

    def test_stm32_pins_on_lpc1769_are_flagged(self):
        """PD7/PC5/PC2 are STM32 names — invalid on LPC1769 (SKR v1.4)."""
        issues = self._run(MIXED_PIN_CFG, "lpc1769")
        self.assertIsNotNone(issues)
        # The STM32 pins must appear (core name, ignoring any !/^ prefix);
        # the LPC1769 P1.15/P1.14 must NOT.
        flagged = " ".join(pin for (_, _, pin, _) in issues)
        self.assertIn("PD7", flagged)
        self.assertIn("PC5", flagged)
        self.assertIn("PC2", flagged)
        self.assertNotIn("P1.15", flagged)
        self.assertNotIn("P1.14", flagged)

    def test_valid_lpc_pins_pass(self):
        issues = self._run(VALID_CFG, "lpc1769")
        self.assertEqual(issues, [])

    def test_unknown_mcu_skips_validation(self):
        """An unrecognized MCU returns None (skip) — we don't false-positive."""
        self.assertIsNone(self._run(VALID_CFG, "totally_unknown_chip"))


class TestArchForMcu(unittest.TestCase):
    def test_known_families(self):
        self.assertEqual(arch_for_mcu("lpc1769"), "lpc176x")
        self.assertEqual(arch_for_mcu("stm32f446"), "stm32")
        self.assertEqual(arch_for_mcu("rp2040"), "rp2040")
        self.assertEqual(arch_for_mcu("atmega2560"), "avr")

    def test_unknown_returns_none(self):
        self.assertIsNone(arch_for_mcu("zzz"))
        self.assertIsNone(arch_for_mcu(""))


class TestPreflightCheck(unittest.TestCase):
    """The deploy gate: malformed configs must abort, valid ones proceed."""

    def test_macros_only_config_aborts_deploy(self):
        """_preflight_check returns False (do not deploy) for the log's broken config."""
        with patch("builtins.open", mock_open(read_data=MACROS_ONLY_CFG)):
            with patch("core.pin_validator.validate_pins_for_mcu", return_value=[]):
                result = _preflight_check("/fake/cfg", {"mcu_type": "lpc1769"}, lambda *a, **k: True)
        self.assertFalse(result)

    def test_valid_config_proceeds(self):
        with patch("builtins.open", mock_open(read_data=VALID_CFG)):
            with patch("core.pin_validator.validate_pins_for_mcu", return_value=[]):
                result = _preflight_check("/fake/cfg", {"mcu_type": "lpc1769"}, lambda *a, **k: True)
        self.assertTrue(result)

    def test_pin_mismatch_can_be_overridden_by_user(self):
        """Soft pin issues prompt the user; 'yes' proceeds, 'no' aborts."""
        fake_issues = [(5, "step_pin", "PD7", "lpc176x")]
        with patch("builtins.open", mock_open(read_data=VALID_CFG)):
            with patch("core.pin_validator.validate_pins_for_mcu", return_value=fake_issues):
                # User says "yes, deploy anyway"
                self.assertTrue(_preflight_check("/fake/cfg", {"mcu_type": "lpc1769"}, lambda *a, **k: True))
                # User says "no"
                self.assertFalse(_preflight_check("/fake/cfg", {"mcu_type": "lpc1769"}, lambda *a, **k: False))


if __name__ == "__main__":
    unittest.main()
