"""Versioned board contracts and the controlled runtime authority boundary."""

from .catalog import BoardCatalog, BoardCatalogError, load_default_catalog
from .models import BoardContract, BoardContractError
from .resolver import BoardResolver, ResolutionResult, ResolutionStatus
from .kconfig import (
    BoardContractBuildContext,
    BoardContractBuildError,
    BoardContractKconfigBuilder,
    BuildProof,
    build_board_contract_shadow,
)
from .deployment import (
    ArtifactTransformation,
    ContractArtifactError,
    ContractDeploymentError,
    ContractIdentityMismatch,
    DeploymentPlan,
    DeploymentStep,
    DeploymentStepId,
    FilenamePolicyError,
    apply_artifact_policy,
    build_artifact_from_proof,
    create_deployment_plan,
    compute_deployment_plan_digest,
    deployment_plan_payload,
    validate_deployment_plan,
)
from .runtime import (
    BoardContractRuntimeBundle,
    BoardContractRuntimeError,
    FirmwareAuthority,
    FirmwareAuthorityDecision,
    build_board_contract_runtime,
    record_board_contract_authority_failure,
    record_firmware_authority,
    resolve_firmware_authority,
)
from .executor import (
    ContractDeploymentExecutionError,
    ContractDeploymentSession,
    ContractDeploymentState,
    DeploymentProof,
    LinuxRemovableMediaProvider,
    LinuxSafeEjector,
    MediaCandidate,
    MoonrakerFirmwareVerifier,
    SafeEjectStatus,
    SdCardDeploymentExecutor,
    UnsupportedContractStrategy,
    write_deployment_proof,
)
from .promotion import (
    DeploymentPromotionError,
    DeploymentPromotionRequest,
    create_deployment_promotion_request,
    write_deployment_promotion_request,
)

__all__ = [
    "BoardCatalog",
    "BoardCatalogError",
    "BoardContract",
    "BoardContractError",
    "BoardContractBuildContext",
    "BoardContractBuildError",
    "BoardContractKconfigBuilder",
    "BoardResolver",
    "BuildProof",
    "ResolutionResult",
    "ResolutionStatus",
    "load_default_catalog",
    "build_board_contract_shadow",
    "ArtifactTransformation",
    "ContractArtifactError",
    "ContractDeploymentError",
    "ContractIdentityMismatch",
    "DeploymentPlan",
    "DeploymentStep",
    "DeploymentStepId",
    "FilenamePolicyError",
    "apply_artifact_policy",
    "build_artifact_from_proof",
    "create_deployment_plan",
    "compute_deployment_plan_digest",
    "deployment_plan_payload",
    "validate_deployment_plan",
    "BoardContractRuntimeBundle",
    "BoardContractRuntimeError",
    "FirmwareAuthority",
    "FirmwareAuthorityDecision",
    "build_board_contract_runtime",
    "record_board_contract_authority_failure",
    "record_firmware_authority",
    "resolve_firmware_authority",
    "ContractDeploymentExecutionError",
    "ContractDeploymentSession",
    "ContractDeploymentState",
    "DeploymentProof",
    "LinuxRemovableMediaProvider",
    "LinuxSafeEjector",
    "MediaCandidate",
    "MoonrakerFirmwareVerifier",
    "SafeEjectStatus",
    "SdCardDeploymentExecutor",
    "UnsupportedContractStrategy",
    "write_deployment_proof",
    "DeploymentPromotionError",
    "DeploymentPromotionRequest",
    "create_deployment_promotion_request",
    "write_deployment_promotion_request",
]
